### ISSUE TITLE
No redirection of bass to LFE (.1) channel

### ISSUE THREAD

**Issue by SpaceAgeHero** [kodi-adsp/adsp.freesurround#1]
Hi,

I've set my speaker output layout to 5.1 in Kodi, but bass is not redirected to my subwoofer.
In the configuration dialog of the original foobar2000 dsp component this is covered via a seperate option, which is not available in Kodi.

**Comment by AlwinEsch** [comment]
Hi @SpaceAgeHero, the LFE bass inside freesurround is not direct selectable on dialog that's true. Reason is that it is part of post process and need normally done by separate add-on's @AchimTuran working on it.

But the part is still inside the code and can be enabled by hand inside "ADSPFreeSurrAddonSettings.xml" (inside freesurround add-on folder)

there you have:

```
        <bassredirection>false</bassredirection>
        <lowcutoff>40.000000</lowcutoff>
        <highcutoff>90.000000</highcutoff>
```

if you set the "bassredirection" to true it is enabled, also you can define the cutoff frequencies there.

**Comment by AlwinEsch** [comment]
I update the README.md in the next time to know this.

**Comment by SpaceAgeHero** [comment]
Hi Alwin,
thanks for the quick tip. I just set bassredirection to true and restarted Kodi.
However it still doesn't work.
Does it work on your system?

**Comment by AlwinEsch** [comment]
Have checked it now, yes works here but was hard for me to hear it with small speakers on test system (my other speaker system from Creative :-( make always in own amplifier the LFE channel).

Maybe you can try a change on frequencies, here it was better on the small with:

```
        <bassredirection>true</bassredirection>
        <lowcutoff>400.000000</lowcutoff>
        <highcutoff>900.000000</highcutoff>
```

**Comment by SpaceAgeHero** [comment]
Indeed. That helped! :-) Thanks.
Why is this supposed be in a seperate Addon by the way?

**Comment by AlwinEsch** [comment]
The DSP system in KODI is planned todo the work in several steps, this is more related to the post process and thought to leave it there confuse if also a addon is present which do the LFE channel. 

I think to look for a better way, may be for a check for presence on post process and if not there to enable here and have visible on skin.

**Comment by AchimTuran** [comment]
> Indeed. That helped! :-) Thanks.

It works, so I will close this issue. Hopefully we will later see this option in the UI.
