### ISSUE TITLE
Make LFE options available in GUI

### ISSUE THREAD

**Issue by SpaceAgeHero** [kodi-adsp/adsp.freesurround#4]
Please make all LFE options available in Addon-options GUI:
- Redirect bass to LFE (.1) channel
- Bass transition lower (Hz)
- Bass transition upper (Hz)

Thanks :-)

**Comment by AlwinEsch** [comment]
Comes in in the next days.

**Comment by AchimTuran** [comment]
@AlwinEsch
Can we close this issue?

**Comment by SpaceAgeHero** [comment]
Any news? :-)

**Comment by AlwinEsch** [comment]
Comes in with https://github.com/kodi-adsp/adsp.freesurround/pull/17
